version: '3.8'

services:
  ollama:
    build: 
      context: .  # assuming Dockerfile is in the current directory
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    mem_limit: 10g  # Allocate 10 GiB of memory to the container
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Rag/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./.env:/app/.env
    depends_on:
      - ollama
    networks:
      - app-network

volumes:
  ollama:

networks:
  app-network:
