version: '3.8'
services:
  backend:
    build:
      context: ./Rag
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SOME_ENV_VAR=value
#    command: /start_backend.sh
#    command: /main.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
